apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  labels:
    app: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: ecommerce:1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "database-service"
            - name: DATABASE_NAME
              value: "ecommerce"
            - name: DATABASE_USER
              value: "admin"
            - name: DATABASE_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP