stages:
  - build
  - test
  - security_scan
  - docker_build
  - image_scan
  - docker_push
  - deploy

variables:
  IMAGE_REPOSITORY: docker.io/sabreensalama/ecommerce
  IMAGE_TAG: $CI_PIPELINE_IID
  IMAGE_NAME: $IMAGE_REPOSITORY:$IMAGE_TAG

build:
  stage: build
  image: python:3.8-bullseye
  before_script:
    - python -m pip install --upgrade pip
    - pip install setuptools==57.5.0 wheel
  script:
    - pip install -r requirements.txt
    - python manage.py check

unit_tests:
  stage: test
  image: python:3.8-bullseye
  before_script:
    - pip install setuptools==57.5.0 wheel
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest

dependency_scan:
  stage: security_scan
  image: python:3.8-bullseye
  script:
    - pip install pip-audit
    - pip-audit || true

docker_build:
  stage: docker_build
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $IMAGE_NAME .
    - docker save -o image.tar $IMAGE_NAME
  artifacts:
    paths:
      - image.tar

image_scan:
  stage: image_scan
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - docker_build
  before_script:
    - apk add --no-cache curl
    - wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    - mv ./bin/trivy /usr/local/bin/
    - docker load -i image.tar
  script:
  - trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME || true

docker_push:
  stage: docker_push
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - docker_build
    - image_scan
  before_script:
    - docker load -i image.tar
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker push $IMAGE_NAME

# deploy_staging:
#   stage: deploy
#   tags:
#     - runner-mac  
#   image: bitnami/kubectl:latest
#   before_script:
#     - mkdir -p ~/.kube
#     - echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config
#     - chmod 600 ~/.kube/config
#   script:
#     - kubectl apply -f kubernetes/deployment.yaml